name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Setup pages
      id: pages
      uses: actions/configure-pages@v4
    - name: Clean docs folder
      run: cargo clean --doc
    - name: Build documentation
      run: cargo doc --no-deps --document-private-items
    # --no-deps won't have a base index file, so create one
    - name: Add redirect
      run: echo '<meta http-equiv="refresh" content="0;url=cube_sniper/index.html">' > target/doc/index.html
    - name: Upload docs artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc

  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Upload docs to github pages
        id: deployment
        uses: actions/deploy-pages@v4
